services:
  shopilent.api:
    container_name: shopilent-api
    image: shopilent.api
    build:
      context: .
      dockerfile: Shopilent.API/Dockerfile
    ports:
      - "${API_PORT_1:-9801}:8080"
    depends_on:
      - postgres
#      - postgres-replica-1
      - redis
      - seq
      - minio
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - Seq__ServerUrl=http://seq:5341
      - ConnectionStrings__PostgreSql=Host=postgres;Database=shopilent;Username=postgres;Password=postgres;Port=5432
      - ConnectionStrings__PostgreSqlReadReplicas__0=Host=postgres-replica-1;Database=shopilent;Username=postgres;Password=postgres;Port=5432
      - Redis__ConnectionString=redis:6379
      - Redis__InstanceName=shopilent_
      - S3__ServiceUrl=http://minio:9000
  
  client:
    container_name: shopilent-client
    image: shopilent.client
    build:
      context: ./Shopilent.Client
      dockerfile: Dockerfile
    ports:
      - "${CLIENT_PORT:-9800}:3000"
    volumes:
      - ./Shopilent.Client:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - API_URL=http://shopilent.api:8080
      - WATCHPACK_POLLING=true
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      - shopilent.api
    restart: unless-stopped
  
  admin:
    container_name: shopilent-admin
    image: shopilent.admin
    build:
      context: ./Shopilent.Admin
      dockerfile: Dockerfile 
    ports:
      - "${ADMIN_PORT:-9802}:5173"
    volumes:
      - ./Shopilent.Admin:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://shopilent.api:8080
    depends_on:
      - shopilent.api
    restart: unless-stopped

  postgres:
    container_name: shopilent-postgres
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-9851}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  postgres-replica-1:
    container_name: shopilent-postgres-replica-1
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_MASTER_HOST=postgres
      - POSTGRES_MASTER_PORT=5432
    ports:
      - "${POSTGRES_REPLICA_PORT_1:-9852}:5432"
    volumes:
      - postgres_replica_1_data:/var/lib/postgresql/data
    depends_on:
      - postgres
    restart: unless-stopped
  
  redis:
    container_name: shopilent-redis
    image: redis:alpine
    ports:
      - "${REDIS_PORT:-9856}:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  minio:
    container_name: shopilent-minio
    image: minio/minio:latest
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    ports:
      - "${MINIO_API_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped

  minio-createbuckets:
    container_name: shopilent-minio-createbuckets
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10 &&
      /usr/bin/mc config host add myminio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} &&
      /usr/bin/mc mb myminio/${S3_BUCKET_NAME} &&
      /usr/bin/mc anonymous set public myminio/${S3_BUCKET_NAME}
      "
    restart: no

  seq:
    container_name: shopilent-seq
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
      - SEQ_ADMIN_USERNAME=${SEQ_ADMIN_USERNAME}
      - SEQ_ADMIN_PASSWORD=${SEQ_ADMIN_PASSWORD}
    ports:
      - "${SEQ_UI_PORT:-9803}:80"
      - "${SEQ_INGEST_PORT:-5341}:5341"
    volumes:
      - seq_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
    name: shopilent_postgres_data
  postgres_replica_1_data:
    name: shopilent_postgres_replica_1_data
  redis_data:
    name: shopilent_redis_data
  minio_data:
    name: shopilen_minio_data
  seq_data:
    name: shopilent_seq_data