services:
  shopilent.api:
    container_name: shopilent-api
    image: shopilent.api
    build:
      context: .
      dockerfile: Shopilent.API/Dockerfile
    ports:
      - "${API_PORT_1}:8080"
    depends_on:
      - postgres
      - postgres-replica-1
      - redis
      - seq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - Seq__ServerUrl=http://seq:5341
      - ConnectionStrings__PostgreSql=Host=postgres;Database=shopilent;Username=postgres;Password=postgres;Port=5432
      - ConnectionStrings__PostgreSqlReadReplicas__0=Host=postgres-replica-1;Database=shopilent;Username=postgres;Password=postgres;Port=5432
      - Redis__ConnectionString=redis:6379
      - Redis__InstanceName=shopilent_

  postgres:
    container_name: shopilent-postgres
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  postgres-replica-1:
    container_name: shopilent-postgres-replica-1
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_MASTER_HOST=postgres
      - POSTGRES_MASTER_PORT=5432
    ports:
      - "${POSTGRES_REPLICA_PORT_1}:5432"
    volumes:
      - postgres_replica_1_data:/var/lib/postgresql/data
    depends_on:
      - postgres
    restart: unless-stopped
  
  redis:
    container_name: shopilent-redis
    image: redis:alpine
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    
  seq:
    container_name: shopilent-seq
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
      - SEQ_ADMIN_USERNAME=${SEQ_ADMIN_USERNAME}
      - SEQ_ADMIN_PASSWORD=${SEQ_ADMIN_PASSWORD}
    ports:
      - "${SEQ_UI_PORT}:80"
      - "${SEQ_INGEST_PORT}:5341"
    volumes:
      - seq_data:/data
    restart: unless-stopped
    
volumes:
  postgres_data:
    name: shopilent_postgres_data
  postgres_replica_1_data:
    name: shopilent_postgres_replica_1_data
  redis_data:
    name: shopilent_redis_data
  seq_data:
    name: shopilent_seq_data