@Shopilent = http://localhost:9801
@Shopilent_Admin_Email = "admin@shopilent.com"
@Shopilent_Admin_Password = "Pa$$word123"
@AccessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhMmU4NGM5OC1kODMyLTRkODYtODBiMy0zNzE4ZTNhNDBkMDEiLCJlbWFpbCI6ImFkbWluQHNob3BpbGVudC5jb20iLCJqdGkiOiI0ODdkMzU4Ny1mNjdkLTRhMjctODBlMS1mZjhlYjZjNThmMDUiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiQWRtaW4gVXNlciIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiSXNTdGFmZiI6InRydWUiLCJleHAiOjE3NTEwMzUzNjMsImlzcyI6IlNob3BpbGVudCIsImF1ZCI6IlNob3BpbGVudENsaWVudCJ9.l6_jeDlEd0zZGX9rMz6UIouxtwKKWOIOnE6U5_2W0ts
@RefreshToken = "VNSvbX1sFEYbKVrTe4u/mSnFxZLaDuUN5q5MFzxzwOTYiJIp4a4dAPEF0XXXHnosNQxjyriEYugmrcPIiJ8ykQ=="

###Register User
POST {{Shopilent}}/api/v1/auth/register
Content-Type: application/json

{
  "email": {{Shopilent_Admin_Email}},
  "password": {{Shopilent_Admin_Password}},
  "firstName": "Admin",
  "lastName": "User",
  "phone": ""
}

###Login User
POST {{Shopilent}}/api/v1/auth/login
Content-Type: application/json

{
  "email": {{Shopilent_Admin_Email}},
  "password": {{Shopilent_Admin_Password}}
}

###Refresh Token
POST {{Shopilent}}/api/v1/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": {{RefreshToken}}
}

###Logout
POST {{Shopilent}}/api/v1/auth/logout
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
  "refreshToken": {{RefreshToken}},
  "reason": "User Logged Out"
}

###Forgot Password
POST {{Shopilent}}/api/v1/auth/forgot-password
Content-Type: application/json

{
  "email": {{Shopilent_Admin_Email}}
}


###Reset Password
@New_Password = "Pa$$word123"
POST {{Shopilent}}/api/v1/auth/reset-password

{
    "token": "",
    "password": {{New_Password}},
    "confirmPassword": {{New_Password}}
}

### Test Endpoint

GET {{Shopilent}}/api/v1/test
Authorization: Bearer {{AccessToken}}

### Products Endpoint
GET {{Shopilent}}/api/v1/products

### Add Product To Cart
POST {{Shopilent}}/api/v1/cart/items
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

{
  "productId": "8c6cf47b-a6b6-46a4-a266-f75e4b8e4ee3",
  "quantity": 1
}

### Add Product Variant To Cart
POST {{Shopilent}}/api/v1/cart/items
Content-Type: application/json

{
  "productId": "9579fbcd-389f-4d16-bd45-e7d675feb435",
  "variantId": "13f0a21b-f1ae-44d2-9022-06fbb543c61f",
  "quantity": 1
}

### Products Endpoint
GET {{Shopilent}}/api/v1/cart?cartId=705679d7-5261-4b6c-b73d-4fa51159088b
#Authorization: Bearer {{AccessToken}}


### Get Cart
GET {{Shopilent}}/api/v1/cart?cartId=017d9c4b-3667-4dde-80ab-a233bebc9adc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiMmVmMzg1Yi1hZWY4LTQxMmUtYTAxOC04ZTVlOTE0MGU0ZWEiLCJlbWFpbCI6Implc3NlQGRlbW8uY29tIiwianRpIjoiYTYwMTgwNmItNjQ2ZC00NjVhLWI2NGYtOWY2M2UyNmFhMzRmIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6Ikplc3NlIE5pY29kZW11cyIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkN1c3RvbWVyIiwiZXhwIjoxNzUxMjAyNDI3LCJpc3MiOiJTaG9waWxlbnQiLCJhdWQiOiJTaG9waWxlbnRDbGllbnQifQ.SSvTjU6nMCYm15z-G-fbzkuLPxYBmTwtSBINdz1Zokw
#Content-Type: application/json
#
#{
#  "cartId": "017d9c4b-3667-4dde-80ab-a233bebc9adc"
#}